#!/usr/bin/python3

import sys
import os

outDir = sys.argv[1]
parser = sys.argv[2]
srcFile = sys.argv[3]

nrArgs = len(sys.argv) -1

if nrArgs != 3:
    print("Number of arguments given: ", nrArgs)
    print("Three arguments are required: output directory, gen_parser binary location, properties.gen location")
    exit(1)

propFile = open(srcFile, 'r')
Lines = propFile.readlines()

for line in Lines:
    line = line.strip()
    if (line != "") and (not line.startswith("#")):
        genName = line.split(':', 1)[0]
        cmd = "'{0}' -o '{1}/autogenerated_{2}.c' '{3}'".format(parser, outDir, genName, line)
        os.system(cmd)
