#!/usr/bin/sh

if [[ $# -lt 3 ]]; then
	echo "Requires at least three arguments (output directory, gen_parser binary location, properties.gen location)"
	exit 1
fi

while read PROP; do
	if [[ ! "$PROP" =~ '#' ]] && [[ $(expr length "$PROP") -ne 0 ]]; then
		IFS=':'
		P=($PROP)
		#IFS=' '
		#echo $PROP | grep BACKGROUND_IMAGE
		"$2" -o "$1/autogenerated_$P.c" "$PROP"
		#"$2" -o "$1/autogenerated_$P.c" "$(grep "^$P:" "$3")"
	fi
done < "$3"

