/*
 * This file is part of LibCSS
 * Licensed under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 * Copyright 2009 John-Mark Bell <jmb@netsurf-browser.org>
 */

#ifndef css_select_propget_h_
#define css_select_propget_h_

#include <libcss/computed.h>
#include "computed.h"
#include "autogenerated_propget.h"

#endif
